_wandb:
    value:
        cli_version: 0.25.1
        e:
            0n63ymlkgc5w62et4eu4g12anbczzmqh:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 16
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "8589934592"
                codePath: /Users/mateobauvir/Desktop/UCL/MASTER1/LELEC2102-Project/LELEC210X-project/classification/tryingClassifier.ipynb
                codePathLocal: tryingClassifier.ipynb
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "547065167872"
                        used: "450375282688"
                email: bauvir.mateo@gmail.com
                executable: /Users/mateobauvir/Desktop/UCL/MASTER1/LELEC2102-Project/LELEC210X-project/.venv/bin/python
                git:
                    commit: 9c07c44c53879b0ba246924d21073c0228e883f4
                    remote: https://github.com/mat-bau/LELEC210X-project
                host: MacBookPro
                memory:
                    total: "17179869184"
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/mateobauvir/Desktop/UCL/MASTER1/LELEC2102-Project/LELEC210X-project/classification/tryingClassifier.ipynb
                python: CPython 3.10.18
                root: /Users/mateobauvir/Desktop/UCL/MASTER1/LELEC2102-Project/LELEC210X-project/classification
                startedAt: "2026-03-13T19:27:25.707066Z"
                writerId: 0n63ymlkgc5w62et4eu4g12anbczzmqh
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.10.18
            "5": 0.25.1
            "8":
                - 1
            "12": 0.25.1
            "13": darwin-arm64
batch_size:
    value: 32
dropout:
    value: 0.5
duration_ms:
    value: 1000
early_stop:
    value: 60
epochs:
    value: 300
extra_aug_passes:
    value: 60
hop_length:
    value: 128
l2_reg:
    value: 0.0001
label_smooth:
    value: 0.1
learning_rate:
    value: 0.0005
mixup_alpha:
    value: 0.3
n_fft:
    value: 512
n_mel:
    value: 64
sample_rate:
    value: 11025
